### ISSUE TITLE
Merge does not work with Batch transformer

### ISSUE THREAD

**Issue by ejls** [mila-udem/fuel#201]
We get a backtrace when running the example code of Merge with an added Batch :

```python
from fuel.datasets import IterableDataset
english = IterableDataset(['Hello world!'])
french = IterableDataset(['Bonjour le monde!'])
from fuel.streams import DataStream
streams = (DataStream(english), DataStream(french))
from fuel.transformers import Batch, Merge
from fuel.schemes import ConstantScheme
streams = tuple(Batch(stream, ConstantScheme(1)) for stream in streams) # <-- XXX
merged_stream = Merge(streams, ('english', 'french'))
next(merged_stream.get_epoch_iterator())
```

**Comment by dwf** [comment]
The backtrace would be helpful...

**Comment by ejls** [comment]
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-361370a0eaf9> in <module>()
----> 1 next(merged_stream.get_epoch_iterator())

/home/ejls/.local/lib/python2.7/site-packages/six.pyc in next(self)
    533 
    534         def next(self):
--> 535             return type(self).__next__(self)
    536 
    537     callable = callable

/home/ejls/work/lisa/fuel/fuel/iterator.pyc in __next__(self)
     30             data = self.data_stream.get_data(next(self.request_iterator))
     31         else:
---> 32             data = self.data_stream.get_data()
     33         if self.as_dict:
     34             return dict(zip(self.data_stream.sources, data))

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.py in get_data(self, request)
    781         return sum(
    782             (data_stream.get_data() for data_stream in self.data_streams),
--> 783             tuple())
    784 
    785 

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.py in <genexpr>((data_stream,))
    780             raise ValueError
    781         return sum(
--> 782             (data_stream.get_data() for data_stream in self.data_streams),
    783             tuple())
    784 

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.py in get_data(self, request)
    584         """Get data from the dataset."""
    585         if request is None:
--> 586             raise ValueError
    587         data = [[] for _ in self.sources]
    588         for i in range(request):

ValueError: 
```

Not sure if helpful, but I also have the following backtrace using Batch followed by Padding (adding the line `streams = tuple(Padding(stream, ()) for stream in streams`) :
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-361370a0eaf9> in <module>()
----> 1 next(merged_stream.get_epoch_iterator())

/home/ejls/.local/lib/python2.7/site-packages/six.pyc in next(self)
    533 
    534         def next(self):
--> 535             return type(self).__next__(self)
    536 
    537     callable = callable

/home/ejls/work/lisa/fuel/fuel/iterator.pyc in __next__(self)
     30             data = self.data_stream.get_data(next(self.request_iterator))
     31         else:
---> 32             data = self.data_stream.get_data()
     33         if self.as_dict:
     34             return dict(zip(self.data_stream.sources, data))

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.pyc in get_data(self, request)
    781         return sum(
    782             (data_stream.get_data() for data_stream in self.data_streams),
--> 783             tuple())
    784 
    785 

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.pyc in <genexpr>((data_stream,))
    780             raise ValueError
    781         return sum(
--> 782             (data_stream.get_data() for data_stream in self.data_streams),
    783             tuple())
    784 

/home/ejls/work/lisa/fuel/fuel/transformers/__init__.pyc in get_data(self, request)
    136         if request is not None:
    137             raise ValueError
--> 138         data = next(self.child_epoch_iterator)
    139 
    140         if self.produces_examples != self.data_stream.produces_examples:

AttributeError: 'Padding' object has no attribute 'child_epoch_iterator'
```

The code was working with commit ed725a7ff9f3d080ef882d4ae7e4373c4984f35a (I didn't bisect, that's just the last version I had before updating)

**Comment by dwf** [comment]
The plot thickens...

```python
In [62]: streams = (DataStream(english, iteration_scheme=SequentialScheme(batch_size=1, examples=1)), DataStream(french, iteration_scheme=SequentialScheme(batch_size=1, examples=1)))

In [63]: merged_stream = Merge(streams, ('english', 'french'))

In [64]: next(merged_stream.get_epoch_iterator())
Out[64]: ('Hello world!', 'Bonjour le monde!')

In [65]: next(merged_stream.get_epoch_iterator())
Out[65]: ()
```

So that doesn't throw a traceback but it is puzzlingly not terminating the iterator when it should. I don't know much about `Merge` and `Batch` (those are kind of @rizar's thing I think) but it looks like something is rotten in Denmark.

**Comment by dwf** [comment]
If you have time to bisect, that'd be great. I have to finish my NIPS reviews by 8.

**Comment by ejls** [comment]
We are rushing for a submission, so I won't have time to do it, sorry.

**Comment by dwf** [comment]
Nevermind, I forgot how easy it is when you have a snippet that raises an exception (thanks for that).

```
297000130ddb5092465598566cca3611edb9d58f is the first bad commit
commit 297000130ddb5092465598566cca3611edb9d58f
Author: Vincent Dumoulin <vi.dumoulin@gmail.com>
Date:   Tue Jul 7 22:54:05 2015 -0400

    Remove assumption that no iteration scheme means provides_examples

:040000 040000 6c239d4355216b8922a957a92aa6c77f94a593c6 7edb5070c31101fc065b6ce9dbca29d19833ca4d M	fuel
:040000 040000 d2fc3f226f685f37ef9e6332c6b064b9ad2f6807 6d3b241c6a063c582bc47807d66cc5f546c72701 M	tests
bisect run success
```

**Comment by dwf** [comment]
@vdumoulin Doc you have any time this week to look at this? Seeing as 297000130ddb5092465598566cca3611edb9d58f found by `git bisect` was one of yours, you might be the most qualified to figure out what went wrong.

**Comment by vdumoulin** [comment]
I'll try to have a look at it either this afternoon or tomorrow morning.

**Comment by vdumoulin** [comment]
It looks like there's an undocumented assumption in `Merge` that the merged data streams produce examples (or, at least, that they have no internal iteration scheme).

It was unwillingly introduced when I made `Merge` subclass from `AbstractDataStream` instead of `Transformer`: since `AbstractDataStream.get_data` is an abstract method, I modified `get_epoch_iterator` so it uses an implementation of `get_data`.

I'll try to think of a solution and, if everything else fails, we could revert to having the former `get_epoch_iterator` implementation and make `get_data` raise a `NotImplementedError`.

**Comment by vdumoulin** [comment]
Here are the two choices we have for a fix: either we adapt `Merge.get_epoch_iterator` and `Merge.get_data` like so

``` python
    def get_epoch_iterator(self, as_dict=False):
        # This is done purely so merged data streams fetch their child epoch
        # iterator
        for data_stream in self.data_streams:
            data_stream.get_epoch_iterator()
        request_iterator_generator = (
            data_stream.iteration_scheme.get_request_iterator()
            if data_stream.iteration_scheme else repeat(None) for
            data_stream in self.data_streams)
        # There is also the case where all data streams have no iteration
        # scheme to consider, which I haven't implemented here
        return DataIterator(self, izip(*request_iterator_generator),
                            as_dict=as_dict)

    def get_data(self, request=None):
        return sum((data_stream.get_data(req) for data_stream, req in
                    izip(self.data_streams, request)),
                   tuple())
```

or we revert to the previous `Merge.get_epoch_iterator` implementation and raise `NotImplementedError` in `Merge.get_data`

``` python
    def get_epoch_iterator(self, **kwargs):
        batches = chain.from_iterable(
            izip(*[data_stream.get_epoch_iterator()
                   for data_stream in self.data_streams]))

        part = partition(len(self.sources), chain.from_iterable(batches))
        as_dict = kwargs.get('as_dict', False)
        if as_dict:
            return imap(dict, starmap(zip, izip(repeat(self.sources), part)))
        else:
            return part

    def get_data(self, request=None):
        raise NotImplementedError
```

**Comment by vdumoulin** [comment]
@dwf do you have a solution preference?

**Comment by rizar** [comment]
@vdumoulin, one thing looks strange to me in your first solution, and it is the fact that in request in `get_data` almost everywhere in Fuel comes from the iteration scheme of the data stream. In your first code snippet the request comes from `Merge`, which implicitly disables the iteration schemes of the merged streams.

Your second proposal disable `get_data`, and I am not sure it is the right to do. We cans still support `get_data`, just that it should only support `None` requests.

Alternatively, we can just merge my minimalistic bug fix from #229, which also seems to solve this issue.

**Comment by rizar** [comment]
I just realized that `get_data` of `Merge` should not call `get_data` of `self.data_streams`, but rather `next` of its multiple (as opposed to `Transformer`) `child_iterator`'s. Will work on that.

**Comment by vdumoulin** [comment]
In my first solution, the `request` argument `get_data` receives is a tuple of requests, which are themselves generated using each of the data streams' request iterators.

**Comment by rizar** [comment]
Please reopen it I am wrong, but I think that we fixed by #229
